### ISSUE TITLE
Implement the Seitz notation based symbol algebra with the help of `TransformationToolbox`. 

### ISSUE THREAD

**Issue by hongyi-zhao** [kutzer/TransformationToolbox#1]
The [Seitz notation](https://www.cryst.ehu.es/cryst/seitz_help.html) is widely used in crystallographic symmetry analysis based on group theory. In nature, as represented [here](https://www.youtube.com/watch?v=nEP-w51oTn0) and [here](https://www.youtube.com/watch?v=Xu7uEIU4ZDU) on YouTube, all the operations represented by Seitz notation form a [Euclidean group](https://en.wikipedia.org/wiki/Euclidean_group).

I want to know if it's possible to do/implement the Seitz notation based symbol algebra with the help of `TransformationToolbox`. 

Any hints/comments will be highly appreciated.

See [here](https://community.wolfram.com/groups/-/m/t/2498389?p_p_auth=q4FBHRKw) for the related discussion.

Regards,
HZ

**Comment by kutzer** [comment]
HZ, it is certainly possible to do/implement the Seitz notation using functions available in the TransformationToolbox. After reviewing the references you provided, this should be a reasonably simple undertaking. I recommend that you create a branch for your exploration.

**Comment by hongyi-zhao** [comment]
Thank you for your reply and confirmation. 

Some additional comments/remarks:

1. What I'm considering at present is mainly based on symbolic algebra. The main scenario is the application of group theory in quantum mechanics, which may be complex derivation/induction/calculation/proof.
2. Non-Abelian symbolic  operation/multiplication judgement problem. In general, the multiplication between two Seitz notations (more generally, [Euclidean group](https://en.wikipedia.org/wiki/Euclidean_group) elements) is not necessarily Abelian, which has brought great troubles and difficulties for the processing of complex symbolic algebraic computation. I don't know if you have a general solution schema to handle this issue.
3. Once I've figured out the problem based on your package, I want to port it to an implementation based on [Wolfram Mathematica](https://www.wolfram.com/mathematica/). I'm not sure whether the realization of the porting is feasible and how difficult it is.

**Comment by kutzer** [comment]
HZ, 

The TransformationToolbox is developed to support a specific set of groups and algebras, specifically those commonly used in the fields of articulated robotics and multiview camera geometry. The primary focus of the TransformationToolbox is N-dimension Special Orthogonal, N-dimensional Special Euclidean, and associated functions. 

Based on the details of your message, I would recommend leveraging Mathematica exclusively for your proposed undertaking. If/when you use definitions contained in the TransformationToolbox, please be sure to appropriately reference the content in any publications, reports, and/or code libraries you generate.

Good luck,

**Comment by hongyi-zhao** [comment]
Thank you for your advice. Would you please give me a specific example of how the `TransformationToolbox` can be used to solve the problems discussed here?

**Comment by kutzer** [comment]
HZ,

Before I can discuss this any further, please send me an email detailing the sponsor organization, university, and/or funding source(s) associated with the effort you have described. Additionally, I will need to know more information about your roll in the project and the names and contact information for the project's principal investigator(s) if you are not the sole PI on this project.

My apologies for the forwardness of this request and I look forward to hearing from you,

- M. Kutzer
